//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.01 at 01:06:51 PM CET 
//


package com.piotrmajcher.jaxblab.invoiceutils.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.piotrmajcher.jaxblab.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _Quantity_QNAME = new QName("", "quantity");
    private final static QName _City_QNAME = new QName("", "city");
    private final static QName _Street_QNAME = new QName("", "street");
    private final static QName _Surname_QNAME = new QName("", "surname");
    private final static QName _Price_QNAME = new QName("", "price");
    private final static QName _PostCode_QNAME = new QName("", "post_code");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _HouseNumber_QNAME = new QName("", "house_number");
    private final static QName _ProductName_QNAME = new QName("", "product_name");
    private final static QName _InvoiceNumber_QNAME = new QName("", "invoice_number");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.piotrmajcher.jaxblab.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress(String street, String houseNumber, String postCode, String city, String country) {
    	Address address = new Address();
    	address.setStreet(street);
    	address.setHouseNumber(houseNumber);
    	address.setPostCode(postCode);
    	address.setCity(city);
    	address.setCountry(country);
        return address;
    }

    /**
     * Create an instance of {@link Buyer }
     * 
     */
    public Buyer createBuyer(String name, String surname, Address address) {
    	Buyer buyer = new Buyer();
    	buyer.setName(name);
    	buyer.setSurname(surname);
    	buyer.setAddress(address);
        return buyer;
    }

    /**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts(String productName, Double price, Integer quantity) {
    	Products products = new Products();
		products.setProductName(productName);
		products.setPrice(BigDecimal.valueOf(price));
		products.setQuantity(BigInteger.valueOf(quantity));
		return products;
    }

    /**
     * Create an instance of {@link Vendor }
     * 
     */
    public Vendor createVendor(String name, String surname, Address address) {
    	Vendor vendor = new Vendor();
    	vendor.setName(name);
    	vendor.setSurname(surname);
    	vendor.setAddress(address);
        return vendor;
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice(String invoiceNumber, Buyer buyer, Vendor vendor, List<Products> productsList) {
    	Invoice invoice = new Invoice();
    	invoice.setInvoiceId(new Date().getTime());
    	invoice.setInvoiceNumber(invoiceNumber);
    	invoice.setBuyer(buyer);
    	invoice.setVendor(vendor);
    	invoice.getProducts().addAll(productsList);
        return invoice;
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "quantity")
    public JAXBElement<BigInteger> createQuantity(BigInteger value) {
        return new JAXBElement<BigInteger>(_Quantity_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "city")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "surname")
    public JAXBElement<String> createSurname(String value) {
        return new JAXBElement<String>(_Surname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "price")
    public JAXBElement<BigDecimal> createPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Price_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "post_code")
    public JAXBElement<String> createPostCode(String value) {
        return new JAXBElement<String>(_PostCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "house_number")
    public JAXBElement<String> createHouseNumber(String value) {
        return new JAXBElement<String>(_HouseNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_name")
    public JAXBElement<String> createProductName(String value) {
        return new JAXBElement<String>(_ProductName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "invoice_number")
    public JAXBElement<String> createInvoiceNumber(String value) {
        return new JAXBElement<String>(_InvoiceNumber_QNAME, String.class, null, value);
    }

}
